/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TroubleshootingIndexRouteImport } from './routes/troubleshooting/index'
import { Route as TroubleshootingNewRouteImport } from './routes/troubleshooting/new'
import { Route as TroubleshootingIdIndexRouteImport } from './routes/troubleshooting/$id/index'
import { Route as TroubleshootingIdEditRouteImport } from './routes/troubleshooting/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingIndexRoute = TroubleshootingIndexRouteImport.update({
  id: '/troubleshooting/',
  path: '/troubleshooting/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingNewRoute = TroubleshootingNewRouteImport.update({
  id: '/troubleshooting/new',
  path: '/troubleshooting/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingIdIndexRoute = TroubleshootingIdIndexRouteImport.update({
  id: '/troubleshooting/$id/',
  path: '/troubleshooting/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingIdEditRoute = TroubleshootingIdEditRouteImport.update({
  id: '/troubleshooting/$id/edit',
  path: '/troubleshooting/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/troubleshooting/new': typeof TroubleshootingNewRoute
  '/troubleshooting/': typeof TroubleshootingIndexRoute
  '/troubleshooting/$id/edit': typeof TroubleshootingIdEditRoute
  '/troubleshooting/$id/': typeof TroubleshootingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/troubleshooting/new': typeof TroubleshootingNewRoute
  '/troubleshooting': typeof TroubleshootingIndexRoute
  '/troubleshooting/$id/edit': typeof TroubleshootingIdEditRoute
  '/troubleshooting/$id': typeof TroubleshootingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/troubleshooting/new': typeof TroubleshootingNewRoute
  '/troubleshooting/': typeof TroubleshootingIndexRoute
  '/troubleshooting/$id/edit': typeof TroubleshootingIdEditRoute
  '/troubleshooting/$id/': typeof TroubleshootingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/troubleshooting/new'
    | '/troubleshooting/'
    | '/troubleshooting/$id/edit'
    | '/troubleshooting/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/troubleshooting/new'
    | '/troubleshooting'
    | '/troubleshooting/$id/edit'
    | '/troubleshooting/$id'
  id:
    | '__root__'
    | '/'
    | '/troubleshooting/new'
    | '/troubleshooting/'
    | '/troubleshooting/$id/edit'
    | '/troubleshooting/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TroubleshootingNewRoute: typeof TroubleshootingNewRoute
  TroubleshootingIndexRoute: typeof TroubleshootingIndexRoute
  TroubleshootingIdEditRoute: typeof TroubleshootingIdEditRoute
  TroubleshootingIdIndexRoute: typeof TroubleshootingIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting/': {
      id: '/troubleshooting/'
      path: '/troubleshooting'
      fullPath: '/troubleshooting/'
      preLoaderRoute: typeof TroubleshootingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting/new': {
      id: '/troubleshooting/new'
      path: '/troubleshooting/new'
      fullPath: '/troubleshooting/new'
      preLoaderRoute: typeof TroubleshootingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting/$id/': {
      id: '/troubleshooting/$id/'
      path: '/troubleshooting/$id'
      fullPath: '/troubleshooting/$id/'
      preLoaderRoute: typeof TroubleshootingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting/$id/edit': {
      id: '/troubleshooting/$id/edit'
      path: '/troubleshooting/$id/edit'
      fullPath: '/troubleshooting/$id/edit'
      preLoaderRoute: typeof TroubleshootingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TroubleshootingNewRoute: TroubleshootingNewRoute,
  TroubleshootingIndexRoute: TroubleshootingIndexRoute,
  TroubleshootingIdEditRoute: TroubleshootingIdEditRoute,
  TroubleshootingIdIndexRoute: TroubleshootingIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
